doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'

        connections:
            default:
                url: "%env(resolve:DATABASE_URL)%"
                driver: "pdo_mysql"
                server_version: "mariadb-10.4.11"
                charset: utf8mb4
            database2:
                url: "%env(resolve:DATABASE2_URL)%"
                driver: "pdo_mysql"
                server_version: "mariadb-10.4.11"
                charset: utf8mb4
    orm:
        entity_managers:
            default:
                connection: default
                mappings:
                Main:
                    is_bundle: false
                    type: annotation
                    dir: "%kernel.project_dir%/src/Entity/Main"
                    prefix: 'App\Entity\Main'
                    alias: Main
            database2:
                connection: database2
                mappings:
                database2:
                    is_bundle: false
                    type: annotation
                    dir: "%kernel.project_dir%/src/Entity/database2"
                    prefix: 'App\Entity\database2'
                    alias: database2
